--
-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
--
-- Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
-- Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
-- Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.
--
-- Find the next triangle number that is also pentagonal and hexagonal.
--

pentagon n = n * (3*n - 1) `div` 2
hexagon  n = n * (2*n - 1)

pentagons = map pentagon [1..]
hexagons  = map hexagon  [1..]

isMatch collection v
    = v `elem` candidates
  where candidates = takeWhile (<= v) collection

isPentagon = isMatch pentagons

matchingAll
    = filter isPentagon hexagons

main
    = print $ take 3 matchingAll
